### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Ciao/latest_checkpoint_0.pth.tar'

### ISSUE THREAD

**Issue by emmimoun** [MEICRS/GDSRec#2]
python main.py
Namespace(dataset_path='datasets/Ciao/', data='Ciao', sigma='0', batch_size=128, embed_dim=256, epoch=100, lr=0.0001, lr_dc=0.1, lr_dc_step=1, test=False)
cuda
Loading data...
  0%|                                                                                                                                                     | 0/100 [00:00<?, ?it/s]C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py:156: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.7422 (avg 0.7422) (62.08 im/s)                                                                                          | 0/1328 [00:00<?, ?it/s] 
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.5316 (avg 0.5331) (1947.79 im/s)                                                                              | 100/1328 [00:07<01:08, 17.83it/s] 
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.4273 (avg 0.5300) (1944.25 im/s)                                                                              | 200/1328 [00:13<01:04, 17.55it/s]
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.4054 (avg 0.5257) (2648.89 im/s)                                                                              | 300/1328 [00:19<00:56, 18.32it/s]
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.5263 (avg 0.5277) (1997.80 im/s)                                                                              | 400/1328 [00:24<00:52, 17.66it/s]
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.5789 (avg 0.5288) (1751.02 im/s)                                                                              | 500/1328 [00:30<00:47, 17.42it/s]
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.3866 (avg 0.5259) (2046.72 im/s)██▏                                                                           | 599/1328 [00:36<00:43, 16.86it/s]
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.6647 (avg 0.5272) (1720.00 im/s)████████████▋                                                                 | 700/1328 [00:42<00:33, 18.50it/s] 
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.5163 (avg 0.5252) (2605.56 im/s)███████████████████████▏                                                      | 800/1328 [00:47<00:29, 18.05it/s]
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.4615 (avg 0.5227) (2012.88 im/s)█████████████████████████████████▌                                            | 900/1328 [00:53<00:24, 17.16it/s]
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.4912 (avg 0.5207) (2031.22 im/s)███████████████████████████████████████████▏                                 | 1000/1328 [00:59<00:18, 17.82it/s]
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.7690 (avg 0.5219) (2012.34 im/s)█████████████████████████████████████████████████████▍                       | 1100/1328 [01:04<00:13, 17.39it/s]
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.4381 (avg 0.5222) (1628.73 im/s)███████████████████████████████████████████████████████████████▋             | 1199/1328 [01:10<00:07, 18.25it/s]
                                                                                                                                                                                  [TRAIN] epoch 1/100 batch loss: 0.5525 (avg 0.5216) (1982.04 im/s)██████████████████████████████████████████████████████████████████████████   | 1300/1328 [01:16<00:01, 18.48it/s] 
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1328/1328 [01:17<00:00, 17.07it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 443/443 [00:16<00:00, 26.51it/s]
DIRECTORY:  ['dataloader.py', 'datasets', 'LICENSE', 'main.py', 'model.py', 'preprocess.py', 'README.md', 'requirements.txt', 'test.py', 'utils.py', '__pycache__']:00, 26.54it/s] 
  0%|                                                                                                                                                     | 0/100 [01:34<?, ?it/s] 
Traceback (most recent call last):
  File "C:\Users\MSI GF\OneDrive\Desktop\GDSRec-main\main.py", line 195, in <module>
    main()
  File "C:\Users\MSI GF\OneDrive\Desktop\GDSRec-main\main.py", line 119, in main
    torch.save(ckpt_dict, args.data+'/latest_checkpoint_'+args.sigma+'.pth.tar')
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 377, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'Ciao/latest_checkpoint_0.pth.tar'

**Comment by findink** [comment]
> FileNotFoundError: [Errno 2] No such file or directory

in main.py , line 33, change it to:
    parser.add_argument('--data', default='datasets/Ciao', help='corresponding to datapath')
